---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    astra_api_url: "https://api.astra.datastax.com/v2/databases"
    astra_auth_token: "[token from devops_auth_post]"
    astra_database_id: "[astra database id]"
  tasks:
    - name: get bundle
      uri:
        url: "{{ astra_api_url }}/{{ astra_database_id }}/secureBundleURL"
        method: POST
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
          Authorization: "Bearer {{ astra_auth_token }}"
        body: ""
        status_code: 200
      register: response_bundle
    - name: debug
      debug:
        var: response_bundle